"updates":
- "directory": "/"
  "groups":
    "all-dependencies":
      "patterns":
      - "*"
  "package-ecosystem": "cargo"
  "schedule":
    "interval": "weekly"
- "directory": "/"
  "groups":
    "all-dependencies":
      "patterns":
      - "*"
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "weekly"
"version": 2
